pokemon:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: main 
      path: './{{ env_var("DUCKDB_DATABASE", "data/staging/data.duckdb") }}'
      extensions: 
        - httpfs

    prod:
      type: duckdb
      schema: agg
      #path: 'md:pokemon'
      path:  "md:dlt_data?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 16
      extensions:
        - httpfs

blog:
  target: dev
  outputs:
    dev:
      type: bigquery 
      location: US
      method: oauth
      schema: blog_info

elementary:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: elementary   # Elementary専用のデータセット名 (スキーマ名として機能)
      threads: 1
      timeout_seconds: 300
      location: US
    prod:
      type: bigquery
      method: oauth
      dataset: elementary   # Elementary専用のデータセット名 (スキーマ名として機能)
      threads: 1
      timeout_seconds: 300
      location: US

    prod:
      type: bigquery 
      location: US
      method: oauth
      schema: blog_info
